### ISSUE TITLE
fit method didn't find the peak I expected

### ISSUE THREAD

**Issue by ftmtas212** [erdogant/findpeaks#26]
Thanks for this great package.

My issue is similar to #16 

here is my image
![tmp_peak](https://github.com/erdogant/findpeaks/assets/12035402/cdfd8986-91eb-4211-bef6-ebad041f47ae)

```
from findpeaks import findpeaks
import os
import cv2
path = os.path.join('tmp_peak.png')
# path=r'tmp_peak.PNG.png'
print(os.path.isfile(path))
fp = findpeaks(method='topology', denoise='lee_enhanced', window=5, whitelist='peak', limit=60)
# X = fp.imread(path)
X = cv2.imread(path)
results = fp.fit(X)
result_df = results['persistence']
peak = result_df.index[result_df['peak']==True].tolist()
print(result_df.loc[peak])
fp.plot_persistence()
fp.plot()
fp.plot_mesh()
```

I have been folowing your provided code, expecting that  (x,y) = (62, 95), (186, 95), (310, 95), (433,95)  would have similar scores, 

However, after trying all the denoise methods, it couldn't find the peak at (310,95)

![Figure_1](https://github.com/erdogant/findpeaks/assets/12035402/f0bb3e73-d3a8-4876-9479-faf9c1c0cca5)
![Figure_2](https://github.com/erdogant/findpeaks/assets/12035402/a3292181-f636-4aeb-9e51-7a86c67e6490)
![Figure_3](https://github.com/erdogant/findpeaks/assets/12035402/8616fd72-c697-4434-b46b-16695b87bc43)

Do you have any suggestions for me?

Thanks!

**Comment by erdogant** [comment]
Great example. I am looking into it.

**Comment by erdogant** [comment]
It took me some time to figure out why these obvious peaks were missed. It turns out that the peaks have exactly the same height and the method loops over the unique values. Or in other words, it only take the first in the unique list. I now fixed this issue by adding a little bit of random noise and making all peaks unique.

update to the latest version with:
`pip install -U findpeaks
` 
from findpeaks import findpeaks
path = r'https://user-images.githubusercontent.com/12035402/274193739-cdfd8986-91eb-4211-bef6-ebad041f47ae.png'
fp = findpeaks(method='topology', denoise='lee_sigma', params={'window': 5}, whitelist='peak', limit=5)
X = fp.imread(path)
results = fp.fit(X)

```
result_df = results['persistence']
peak = result_df.index[result_df['peak']==True].tolist()
print(result_df.loc[peak])
print(result_df.shape)
fp.plot_persistence()
fp.plot(figsize=(25, 14), text=False, marker='x', color='#ff0000', figure_order='vertical')

```

![image](https://github.com/erdogant/findpeaks/assets/31008129/8947b49f-e226-47d3-8738-ad4708b46283)
