### ISSUE TITLE
First and last data point always labeled as a valley

### ISSUE THREAD

**Issue by Kenneth-new-user** [erdogant/findpeaks#30]
The first and last points in a series are always labelled as a valley. See the output of this series modified from the 1d example:

```
from findpeaks import findpeaks
# Data
X = [1153,672,501,1068,1110,574,135,23,3,47,252,812,1182]
# Initialize
fp = findpeaks(lookahead=1)
results = fp.fit(X)
# Plot
fp.plot()
results.get('df')
```

![image](https://github.com/erdogant/findpeaks/assets/140436875/303791fc-b3c4-41bf-88dc-cc773e57ecfa)

**Comment by erdogant** [comment]
I've looked into it. Firstly, I agree that these points aren't valleys. However, it's important to label the start and stop points because of how the entire signal is labeled. Without those points, the green and purple segments wouldn't have been distinguished; they would have received the same label. My suggestion for now is to manually remove these points.

`results['df'].iloc[1:-1]
`
